name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Trigger on PR events for the main branch

env:
  ACTIONS_STEP_DEBUG: true  # Enable debug logging for more insights

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    timeout-minutes: 90  # Increased timeout to 1.5 hours
    name: Build and Deploy Job

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false  # Set to true if using Git Large File Storage

      # Step 2: Install dependencies (Optional, only if your app needs it)
      - name: Install Dependencies
        run: npm install  # Modify if you use yarn or another package manager

      # Step 3: Build the app (Adjust based on your build tool, e.g., npm build)
      - name: Build the Application
        run: npm run build --if-present  # Runs the build script if defined in package.json

      # Step 4: Deploy the app to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1  # Use the latest stable version
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_OCEAN_09FDCA10F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # For GitHub integrations (PR comments, etc.)
          action: "upload"
          
          # Repository/Build Configurations
          app_location: "./blog"  # Location of your app's source code
          api_location: ""  # Optional: Location of API if applicable
          output_location: ""  # Adjust if your build outputs to a different folder

          # Deployment timeout and verbosity for detailed logs
          timeout: 2700  # 45 minutes
          verbose: true  # Enable verbose logging

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1  # Use the latest stable version
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_OCEAN_09FDCA10F }}
          action: "close"
