name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Trigger on PR events for the main branch

env:
  ACTIONS_STEP_DEBUG: true  # Enable debug logging for insights

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    timeout-minutes: 90  # Set to 1.5 hours
    name: Build and Deploy Job

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false  # Set to true if using large files

      # Step 2: List directory contents (for debugging paths)
      - name: List Directory Contents
        run: ls -R  # Check directory structure to confirm paths

      # Step 3: Install dependencies from the 'blog/' folder
      - name: Install Dependencies
        run: npm install
        working-directory: ./blog  # Ensures npm uses the correct folder

      # Step 4: Build the app from the 'blog/' folder
      - name: Build the Application
        run: npm run build --if-present
        working-directory: ./blog  # Builds using the correct path

      # Step 5: Deploy the app to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1  # Use the latest stable version
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_OCEAN_09FDCA10F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"  # Explicitly specify the action
          
          app_location: "./blog"  # Location of your app's code
          output_location: ".next"  # Output directory for Next.js

          timeout: 2700  # 45 minutes for deployment
          verbose: true  # Enable verbose logging

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1  # Latest stable version
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_OCEAN_09FDCA10F }}
          action: "close"
